update pkg

diff --git a/usr/bin/touchegg-autostart b/usr/bin/touchegg-autostart
--- a/usr/bin/touchegg-autostart
+++ b/usr/bin/touchegg-autostart
@@ -1,14 +1,60 @@
-#! /bin/bash
+#!/usr/bin/env bash
 
-set -x
+#############################################################################################################################################################################
+#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
+#                                                                                                                                                                           #
+#   Copyright <2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
+#                                                                                                                                                                           #
+#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
+#                                                                                                                                                                           #
+#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
+#                                                                                                                                                                           #
+#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
+#       in the documentation and/or other materials provided with the distribution.                                                                                         #
+#                                                                                                                                                                           #
+#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
+#       without specific prior written permission.                                                                                                                          #
+#                                                                                                                                                                           #
+#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
+#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
+#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
+#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
+#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
+#############################################################################################################################################################################
 
-# -- If touchegg is already running, kill it.
 
-killall touchegg
+# -- Exit on errors.
 
-# -- Start touchegg first as daemon then as client.
+set -eu
 
-touchegg --daemon 2>&1 &
-touchegg --client 2>&1 &
+kill_touchegg() {
+    if pgrep touchegg > /dev/null; then
+        killall touchegg
+    fi
+}
 
-exit 0
+start_touchegg() {
+    touchegg --daemon 2>&1 &
+    MAX_RETRIES=10
+    RETRY_COUNT=0
+
+    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
+        touchegg --client 2>&1
+        if [ $? -ne 0 ]; then
+            echo "touchegg --client crashed. Restarting... (Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)"
+            ((RETRY_COUNT++))
+            sleep 1
+        else
+            echo "touchegg --client exited normally."
+            break
+        fi
+    done
+
+    if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+        echo "touchegg --client crashed too many times. Exiting..."
+    fi
+}
+
+kill_touchegg
+
+start_touchegg
